add migration
cultuurnet/udb3-backend pull request #1680
Opened 2024-04-08 07:22 UTC by JonasVHG

### Added

- `Migration`: to add mapping table between KinepolisID & publiq ID

---
Ticket: https://jira.uitdatabank.be/browse/III-6079

2024-04-08 08:37 UTC, LucWollants commented on app/Migrations/Version20240402125210.php
> +        $table = $schema->createTable('movie_mapping');
Make this more explicit it is related to Kinepolis, for example `kinepolis_movie_mapping`

2024-04-08 08:40 UTC, simon-debruijn requested changes

2024-04-08 08:40 UTC, simon-debruijn commented on app/Migrations/Version20240402125210.php
> +        $table->addIndex(['movie_id']);
See

https://github.com/cultuurnet/udb3-backend/pull/1681/files#r1555400808

2024-04-09 07:24 UTC, LucWollants approved these changes

2024-04-10 07:31 UTC, simon-debruijn approved these changes

2024-04-10 07:31 UTC, merged