III-6212 Integrate Keycloack management to search users
cultuurnet/udb3-backend pull request #1712
Opened 2024-06-10 13:53 UTC by LucWollants

### Added
- Implemented user resolver with Keycloack

### Note
- This also requires a config change https://github.com/cultuurnet/appconfig/pull/661
- Take into account that nickname is not yet provided on Keycloack

---
Ticket: https://jira.uitdatabank.be/browse/...

2024-06-10 14:42 UTC, JonasVHG approved these changes

2024-06-11 13:06 UTC, grubolsch requested changes

2024-06-11 17:03 UTC, LucWollants commented on app/Console/Command/KeycloackCommand.php
> +final class KeycloackCommand extends Command
To test for now because no actual code is executed.

2024-06-11 17:12 UTC, LucWollants commented on app/Console/Command/KeycloackCommand.php
> +        if ($input->getOption('id')) {
I improved the stability.

2024-06-12 07:59 UTC, grubolsch approved these changes

2024-06-12 10:37 UTC, merged