III-6453 Provide fallback when calendar type does not match sub event count
cultuurnet/udb3-backend pull request #1951
Opened 2024-12-20 13:58 UTC by LucWollants

### Changed
- Provided fallback when calendar type does not match sub event count

---
Ticket: https://jira.uitdatabank.be/browse/III-6453

2025-01-02 09:21 UTC, simon-debruijn requested changes

2025-01-02 09:21 UTC, simon-debruijn commented on src/Model/Serializer/ValueObject/Calendar/CalendarSerializer.php
> +        if ($calendarType->sameAs(CalendarType::single()) && count($subEvents) > 1) {
Wouldn't a better solution be creating new events in the event store to fix these events?

2025-01-06 07:46 UTC, LucWollants commented on src/Model/Serializer/ValueObject/Calendar/CalendarSerializer.php
> +        if ($calendarType->sameAs(CalendarType::single()) && count($subEvents) > 1) {
This code is used to read the JSON payload from the existing and new events inside the event store. The new events which are created with commands with better validation will have the correct structure.

2025-01-06 09:02 UTC, simon-debruijn approved these changes

2025-01-06 09:22 UTC, merged